#--
# DO NOT MODIFY!!!!
# This file is automatically generated by rex 1.0.5
# from lexical definition file "lib/unit/lexer_definition.rex".
#++

require 'racc/parser'
class Unit::Lexer < Racc::Parser
  require 'strscan'

  class ScanError < StandardError ; end

  attr_reader   :lineno
  attr_reader   :filename
  attr_accessor :state

  def scan_setup(str)
    @ss = StringScanner.new(str)
    @lineno =  1
    @state  = nil
  end

  def action
    yield
  end

  def scan_str(str)
    scan_setup(str)
    do_parse
  end
  alias :scan :scan_str

  def load_file( filename )
    @filename = filename
    open(filename, "r") do |f|
      scan_setup(f.read)
    end
  end

  def scan_file( filename )
    load_file(filename)
    do_parse
  end


  def next_token
    return if @ss.eos?
    
    # skips empty actions
    until token = _next_token or @ss.eos?; end
    token
  end

  def _next_token
    text = @ss.peek(1)
    @lineno  +=  1  if text == "\n"
    token = case @state
    when nil
      case
      when (text = @ss.scan(/[ \t]+/i))
        ;

      when (text = @ss.scan(/[-+]?[0-9]*\.?[0-9]+/i))
         action { [:SCALAR, BigDecimal.new(text, 10)] }

      when (text = @ss.scan(/\b(?:gm|gram)\b/i))
         action { [:MASS_UOM, 'g'] }

      when (text = @ss.scan(/\b(?:mcg|mg|g)\b/i))
         action { [:MASS_UOM, text] }

      when (text = @ss.scan(/\b(?:ml|l)\b/i))
         action { [:VOLUME_UOM, text] }

      when (text = @ss.scan(/\b(?:unit|u)\b/i))
         action { [:UNIT_UOM, text] }

      when (text = @ss.scan(/\b(?:ea)\b/i))
         action {[:UNITLESS_UOM, text] }

      when (text = @ss.scan(/\b(?:meq|eq)\b/i))
         action {[:EQUIVALENCE_UOM, text] }

      when (text = @ss.scan(/\//i))
         action { [:SLASH, text] }

      when (text = @ss.scan(/%/i))
         action { [:PERCENT, text] }

      else
        text = @ss.string[@ss.pos .. -1]
        raise  ScanError, "can not match: '" + text + "'"
      end  # if

    else
      raise  ScanError, "undefined state: '" + state.to_s + "'"
    end  # case state
    token
  end  # def _next_token

  def tokenize(code)
    scan_setup(code.downcase)
    @tokens = []
    while token = next_token
      @tokens << token
    end
    @tokens
  end
end # class
