#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.12
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require_relative 'lexer'

module Unit
  class Parser < Racc::Parser

module_eval(<<'...end parser_definition.y/module_eval...', 'parser_definition.y', 34)
  def parse(input)
    #Takes the results from the lexer's tokenize method and returns stuff
    @tokens = input
    do_parse
  end

  def next_token
    @tokens.shift
  end
...end parser_definition.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    14,    15,    16,    17,    21,    21,    23,    20,    10,    13,
    18,    12,    11,    15 ]

racc_action_check = [
    10,    10,    10,    10,    13,    12,    13,    12,     0,     8,
    11,     6,     1,    21 ]

racc_action_pointer = [
     6,    12,   nil,   nil,   nil,   nil,     4,   nil,     2,   nil,
    -3,    10,     3,     2,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     9,   nil,   nil ]

racc_action_default = [
   -17,   -17,    -1,    -2,    -3,    -4,    -5,    -6,    -7,    -8,
   -17,   -17,   -17,   -17,   -13,   -14,   -15,   -16,    24,    -9,
   -10,   -17,   -11,   -12 ]

racc_goto_table = [
     7,     5,     3,     4,     2,     6,     1,     8,     9,   nil,
   nil,   nil,    19,    22 ]

racc_goto_check = [
     7,     5,     3,     4,     2,     6,     1,     8,     9,   nil,
   nil,   nil,     7,     7 ]

racc_goto_pointer = [
   nil,     6,     4,     2,     3,     1,     5,     0,     7,     8 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 9, :_reduce_none,
  1, 9, :_reduce_none,
  1, 9, :_reduce_none,
  1, 9, :_reduce_none,
  1, 9, :_reduce_none,
  1, 9, :_reduce_none,
  1, 9, :_reduce_none,
  1, 9, :_reduce_none,
  3, 10, :_reduce_9,
  3, 11, :_reduce_10,
  3, 12, :_reduce_11,
  3, 13, :_reduce_12,
  2, 14, :_reduce_13,
  2, 15, :_reduce_14,
  2, 16, :_reduce_15,
  2, 17, :_reduce_16 ]

racc_reduce_n = 17

racc_shift_n = 24

racc_token_table = {
  false => 0,
  :error => 1,
  :SCALAR => 2,
  :MASS_UOM => 3,
  :VOLUME_UOM => 4,
  :UNIT_UOM => 5,
  :PERCENT => 6,
  :SLASH => 7 }

racc_nt_base = 8

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "SCALAR",
  "MASS_UOM",
  "VOLUME_UOM",
  "UNIT_UOM",
  "PERCENT",
  "SLASH",
  "$start",
  "valid_unit",
  "concentration",
  "concentration_no_denom_scalar",
  "unit_concentration",
  "unit_concentration_no_denom_scalar",
  "mass",
  "volume",
  "unit",
  "percent" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

module_eval(<<'.,.,', 'parser_definition.y', 13)
  def _reduce_9(val, _values, result)
     return Concentration.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 14)
  def _reduce_10(val, _values, result)
     return Concentration.new(val[0], Volume.new(1, val[2])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 16)
  def _reduce_11(val, _values, result)
     return Concentration.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 17)
  def _reduce_12(val, _values, result)
     return Concentration.new(val[0], Volume.new(1, val[2])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 19)
  def _reduce_13(val, _values, result)
     return Mass.new(val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 21)
  def _reduce_14(val, _values, result)
     return Volume.new(val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 23)
  def _reduce_15(val, _values, result)
     return Unit.new(val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 25)
  def _reduce_16(val, _values, result)
     return Concentration.new(Mass.new(val[0] * 10, 'mg'), Volume.new(1, 'ml')) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module Unit
