#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.12
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require_relative 'lexer'

module Unit
  class Parser < Racc::Parser

module_eval(<<'...end parser_definition.y/module_eval...', 'parser_definition.y', 59)
  def parse(input)
    #Takes the results from the lexer's tokenize method and returns stuff
    @tokens = input
    do_parse
  end

  def next_token
    @tokens.shift
  end
...end parser_definition.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    27,    28,    29,    30,    32,    31,    26,    33,    37,    37,
    41,    43,    37,    37,    36,    39,    19,    25,    23,    34,
    22,    24,    21,    20,    45,    46,    47,    28,    33,    48,
    49,    50 ]

racc_action_check = [
    19,    19,    19,    19,    19,    19,    19,    19,    23,    24,
    23,    24,    21,    22,    21,    22,     0,    17,    15,    20,
    14,    16,    12,     1,    25,    26,    33,    37,    45,    46,
    48,    49 ]

racc_action_pointer = [
    14,    23,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    13,   nil,    11,     9,    12,     6,   nil,    -3,
    19,    10,    11,     6,     7,    22,    23,   nil,   nil,   nil,
   nil,   nil,   nil,    24,   nil,   nil,   nil,    23,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    18,    26,   nil,    21,    27,
   nil ]

racc_action_default = [
   -35,   -35,    -1,    -2,    -3,    -4,    -5,    -6,    -7,    -8,
    -9,   -10,   -11,   -12,   -13,   -14,   -15,   -16,   -17,   -35,
   -35,   -35,   -35,   -35,   -35,   -35,   -35,   -28,   -29,   -30,
   -31,   -32,   -33,   -35,    51,   -18,   -19,   -35,   -21,   -22,
   -25,   -26,   -23,   -24,   -27,   -35,   -35,   -34,   -35,   -35,
   -20 ]

racc_goto_table = [
    18,    10,     4,     5,     6,    13,     7,     8,     9,     3,
    11,    12,     2,    14,    15,    16,    17,     1,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    44,    35,    38,    40,    42 ]

racc_goto_check = [
    18,    10,     4,     5,     6,    13,     7,     8,     9,     3,
    11,    12,     2,    14,    15,    16,    17,     1,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    18,    13,    13,    13,    13 ]

racc_goto_pointer = [
   nil,    17,    12,     9,     2,     3,     4,     6,     7,     8,
     1,    10,    11,     5,    13,    14,    15,    16,     0 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 13, :_reduce_none,
  1, 13, :_reduce_none,
  1, 13, :_reduce_none,
  1, 13, :_reduce_none,
  1, 13, :_reduce_none,
  1, 13, :_reduce_none,
  1, 13, :_reduce_none,
  1, 13, :_reduce_none,
  1, 13, :_reduce_none,
  1, 13, :_reduce_none,
  1, 13, :_reduce_none,
  1, 13, :_reduce_none,
  1, 13, :_reduce_none,
  1, 13, :_reduce_none,
  1, 13, :_reduce_none,
  1, 13, :_reduce_none,
  1, 13, :_reduce_none,
  3, 14, :_reduce_18,
  3, 15, :_reduce_19,
  6, 22, :_reduce_20,
  3, 16, :_reduce_21,
  3, 17, :_reduce_22,
  3, 20, :_reduce_23,
  3, 21, :_reduce_24,
  3, 18, :_reduce_25,
  3, 19, :_reduce_26,
  3, 23, :_reduce_27,
  2, 24, :_reduce_28,
  2, 25, :_reduce_29,
  2, 26, :_reduce_30,
  2, 27, :_reduce_31,
  2, 29, :_reduce_32,
  2, 28, :_reduce_33,
  3, 30, :_reduce_34 ]

racc_reduce_n = 35

racc_shift_n = 51

racc_token_table = {
  false => 0,
  :error => 1,
  :SCALAR => 2,
  :MASS_UOM => 3,
  :VOLUME_UOM => 4,
  :UNIT_UOM => 5,
  :UNITLESS_UOM => 6,
  :EQUIVALENCE_UOM => 7,
  :PERCENT => 8,
  :SLASH => 9,
  :COLON => 10,
  :SEPERATOR => 11 }

racc_nt_base = 12

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "SCALAR",
  "MASS_UOM",
  "VOLUME_UOM",
  "UNIT_UOM",
  "UNITLESS_UOM",
  "EQUIVALENCE_UOM",
  "PERCENT",
  "SLASH",
  "COLON",
  "SEPERATOR",
  "$start",
  "valid_unit",
  "concentration",
  "concentration_no_denom_scalar",
  "unit_concentration",
  "unit_concentration_no_denom_scalar",
  "unit_less_concentration",
  "unit_less_concentration_no_denom_scalar",
  "equivalence_concentration",
  "equivalence_concentration_no_denom_scalar",
  "rational_concentration",
  "mixed_solution",
  "mass",
  "volume",
  "unit",
  "unitless",
  "equivalence",
  "percent",
  "solution" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

module_eval(<<'.,.,', 'parser_definition.y', 22)
  def _reduce_18(val, _values, result)
     return Concentration.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 23)
  def _reduce_19(val, _values, result)
     return Concentration.new(val[0], Volume.new(1, val[2])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 24)
  def _reduce_20(val, _values, result)
     return Concentration.new(Mass.new(val[0], val[3]), Volume.new(val[2], val[5])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 26)
  def _reduce_21(val, _values, result)
     return Concentration.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 27)
  def _reduce_22(val, _values, result)
     return Concentration.new(val[0], Volume.new(1, val[2])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 29)
  def _reduce_23(val, _values, result)
     return Concentration.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 30)
  def _reduce_24(val, _values, result)
     return Concentration.new(val[0], Volume.new(1, val[2])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 32)
  def _reduce_25(val, _values, result)
     return Concentration.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 33)
  def _reduce_26(val, _values, result)
     return Concentration.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 35)
  def _reduce_27(val, _values, result)
     return val[0] + val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 37)
  def _reduce_28(val, _values, result)
     return Mass.new(val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 39)
  def _reduce_29(val, _values, result)
     return Volume.new(val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 41)
  def _reduce_30(val, _values, result)
     return Unit.new(val[0], 'unit') 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 43)
  def _reduce_31(val, _values, result)
     return Unit.new(val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 45)
  def _reduce_32(val, _values, result)
     return Concentration.new(Mass.new(val[0] * 10, 'mg'), Volume.new(1, 'ml')) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 47)
  def _reduce_33(val, _values, result)
     return Equivalence.new(val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser_definition.y', 49)
  def _reduce_34(val, _values, result)
     return Concentration.new(Mass.new(val[0] * 1000, 'mg'), Volume.new(val[2], 'ml')) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module Unit
